"use client";

import { useState } from "react";
import type { Run } from "../../_lib/run";

// MISSION 05 — VERIFY
// The judge MUST inspect the evidence, state binding, and checksum to
// confirm understanding. Each row must be clicked at least once.

type EvidenceRow = {
  id: string;
  label: string;
  value: string;
  source: "verified" | "reported" | "derived" | "simulated";
  detail: string;
};

function evidenceRows(run: Run): EvidenceRow[] {
  const commit = run.data.commit;
  const execute = run.data.execute;
  const blocked = commit?.outcome !== "AUTHORIZED" || execute?.disposition === "BLOCKED_NO_AUTHORITY";

  if (blocked) {
    return [
      { id: "policy", label: "Policy", value: "Refund ≤ $100", source: "verified", detail: "The campaign policy used for this public-safe scenario." },
      { id: "commit", label: "Commit outcome", value: commit?.outcome ?? "MISSING", source: "verified", detail: "The recorded Commit decision controls whether Level 04 may invoke a substrate." },
      { id: "authority", label: "Execution authority", value: "NOT ESTABLISHED", source: "derived", detail: "A rejected or missing Commit outcome grants no authority to cause a consequence." },
      { id: "substrate", label: "Selected substrate", value: "NONE", source: "verified", detail: "The execution loadout was never invoked." },
      { id: "observation", label: "Observed effect", value: "NO EFFECT ATTEMPTED", source: "verified", detail: "Non-execution is the expected, evidence-backed consequence of refusal." },
    ];
  }

  const successful = [...(execute?.attempts ?? [])].reverse().find((attempt) => attempt.result === "SUCCESS");
  const substrate = successful?.substrate ?? "NONE";
  return [
    { id: "policy", label: "Policy", value: "Refund ≤ $100", source: "verified", detail: "The campaign policy used for this public-safe scenario." },
    { id: "authority", label: "Commit outcome", value: "AUTHORIZED", source: "verified", detail: "The exact simulated consequence passed the campaign's Commit checks." },
    { id: "capability", label: "Capability", value: "refund:create PRESENT", source: "reported", detail: "Reported capability is evidence of availability, never authority by itself." },
    { id: "binding", label: "Simulation binding", value: "INPUT ↔ AUTHORIZED EFFECT", source: "derived", detail: "The selected target must match the authorized effect fingerprint in this public-safe simulation." },
    { id: "receipt", label: "Simulation receipt", value: `sim_${substrate.toLowerCase()}_receipt`, source: "simulated", detail: `Generated by the Level 04 ${substrate} simulation. This is not a live control-room execution receipt.` },
  ];
}

export function Mission05Verify({
  run,
  onComplete,
}: {
  run: Run;
  onComplete: (inspections: string[]) => void;
}) {
  const [inspected, setInspected] = useState<Set<string>>(new Set(run.data.verify?.inspections ?? []));
  const [open, setOpen] = useState<string | null>(null);
  const [confirmed, setConfirmed] = useState(run.data.verify?.completed ?? false);
  const rows = evidenceRows(run);
  const blocked = run.data.commit?.outcome !== "AUTHORIZED" || run.data.execute?.disposition === "BLOCKED_NO_AUTHORITY";

  function click(id: string) {
    setInspected((s) => new Set(s).add(id));
    setOpen(id);
  }

  function confirm() {
    setConfirmed(true);
    onComplete([...inspected]);
  }

  const allInspected = rows.every((r) => inspected.has(r.id));

  return (
    <div>
      <div className="lvl-hero">
        <div className="num">05</div>
        <div className="word">
          <p className="tagline">Inspect the resulting state</p>
          <h1 className="verb">VERIFY</h1>
          <p className="proves"><strong>PROVES</strong> Don’t trust it — prove it</p>
        </div>
      </div>

      <div className="lvl-body">
        <div className="lvl-body-grid split">
          <div>
            <p className="lvl-h3">Evidence rows <strong>click to inspect each</strong></p>
            <p style={{ fontSize: 12, color: "var(--lvl-muted)", margin: "0 0 14px" }}>
              Each row is bound to a source. Click them all. Confirm your understanding.
            </p>
            <div className="m05-list">
              {rows.map((r) => {
                const isInspected = inspected.has(r.id);
                const isOpen = open === r.id;
                return (
                  <button
                    key={r.id}
                    type="button"
                    className={`m05-row ${isOpen ? "open" : ""} ${isInspected ? "inspected" : ""}`}
                    onClick={() => click(r.id)}
                  >
                    <span className={`m05-source source-${r.source}`}>{r.source}</span>
                    <span className="m05-content">
                      <span className="m05-label">{r.label}</span>
                      <code className="m05-value">{r.value}</code>
                      {isOpen ? <p className="m05-detail">{r.detail}</p> : null}
                    </span>
                    <span className="m05-mark">{isInspected ? "✓" : "▸"}</span>
                  </button>
                );
              })}
            </div>
            <div style={{ marginTop: 14, display: "flex", gap: 10, alignItems: "center" }}>
              <span style={{ fontSize: 11, color: "var(--lvl-muted)", letterSpacing: ".12em", textTransform: "uppercase" }}>
                {inspected.size} / {rows.length} inspected
              </span>
              {allInspected ? (
                <button type="button" className="lvl-advance" onClick={confirm}>
                  <span className="arrow">▸</span>
                  <span className="verb-text">I confirm. Proceed to ABSORB.</span>
                  <span className="label">06 / ABSORB</span>
                </button>
              ) : (
                <span style={{ fontSize: 11, color: "var(--lvl-dim)", letterSpacing: ".12em", textTransform: "uppercase" }}>
                  Click every row to confirm.
                </span>
              )}
            </div>
            {confirmed ? (
              <p style={{ marginTop: 10, fontSize: 11, color: "var(--lvl-acid)", letterSpacing: ".12em", textTransform: "uppercase" }}>
                ✓ Verified. Stored in run state.
              </p>
            ) : null}
          </div>

          <div>
            <p className="lvl-h3">Xact’s consequence boundary <strong>{blocked ? "held" : "simulated"}</strong></p>
            <div className="lvl-card">
              <span className="k">{blocked ? "ZERO-EFFECT RECORD" : "PUBLIC-SAFE SIMULATION"}</span>
              <code style={{ fontFamily: "var(--mono)", fontSize: 13, color: "var(--lvl-acid)" }}>
                {blocked ? "NO AUTHORITY → NO EXECUTION" : "AUTHORIZED → SIMULATED EFFECT"}
              </code>
              <p style={{ fontSize: 11, color: "var(--lvl-muted)", margin: "8px 0 0" }}>
                {blocked
                  ? "The refused Commit never entered an execution adapter. No target was touched and no receipt was invented."
                  : "This campaign level demonstrates routing and target binding without mutating the real control-room runtime. Use Control Room for live public-safe runtime evidence."}
              </p>
            </div>
            <div className="lvl-stat-block" style={{ marginTop: 12 }}>
              <span className="k">VERIFICATION STATUS</span>
              <span className="v" style={{ color: allInspected ? "var(--lvl-acid)" : "var(--lvl-dim)" }}>
                {allInspected ? "VERIFIED" : "IN PROGRESS"}
              </span>
              <span className="delta">All five rows identify verified, derived, reported, or simulated provenance.</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
