import type { ControlRoomScenario } from "./types";

export const scenarios: ControlRoomScenario[] = [
  {
    id: "authorized",
    index: "01",
    label: "Authorized",
    title: "Refund within verified policy",
    description: "Every commit-relevant fact resolves deterministically. Authority is current and the effect is independently verified.",
    status: "AUTHORIZED",
    request: {
      id: "req_84D1",
      intent: "Refund a delayed shipment",
      actor: "support.agent / ana",
      target: "order #XC-2048",
      proposedEffect: "Issue $42.00 to original payment method",
    },
    resolution: {
      resolved: [
        { label: "Order total", value: "$86.40", source: "verified", provenance: "Orders API · ord_2048" },
        { label: "Delay", value: "6 days", source: "derived", provenance: "Promised vs delivered timestamps" },
        { label: "Refund limit", value: "$75.00", source: "verified", provenance: "Commerce Policy v3.4" },
      ],
      unresolved: [],
      commitConstraints: [{ label: "Original rail required", detail: "Refund must return to the original payment rail.", condition: "required", satisfied: true }],
    },
    evidence: [
      { id: "ev_101", claim: "Order was delivered six days late", source: "Orders API / delivery record", kind: "derived", boundAt: "10:42:12.006" },
      { id: "ev_102", claim: "Actor may refund up to $75", source: "Commerce Policy v3.4", kind: "verified", boundAt: "10:42:12.018" },
      { id: "ev_103", claim: "Original payment rail is available", source: "Payments API / pi_882", kind: "verified", boundAt: "10:42:12.024" },
    ],
    reasoning: { involved: false, summary: "Not invoked", output: "U = 0. No semantic interpretation required." },
    commit: {
      summary: "Authority, evidence, and state binding all pass.",
      policy: "PASS · $42.00 ≤ $75.00",
      authority: "PASS · actor authority allowed",
      capability: "PASS · refund:create",
      stateBinding: "PASS · candidate state is current",
      baseHash: "8b7c…e21a",
      currentHash: "8b7c…e21a",
    },
    decision: { finality: "PASSED", label: "Effect may proceed", nextStep: "Select an execution substrate and verify the simulated effect." },
    execution: { selected: "WEBMCP", effect: "refund.create", executed: true, receipt: "rcpt_WM_729A" },
    trace: [
      { phase: "Resolve", outcome: "R3 · U0 · C1", detail: "Facts resolved from governed sources", at: "10:42:12.031", state: "complete" },
      { phase: "Reason", outcome: "Skipped", detail: "No unresolved semantics", at: "10:42:12.033", state: "complete" },
      { phase: "Commit", outcome: "Authorized", detail: "Re-read, authority, and stale guard passed", at: "10:42:12.049", state: "complete" },
      { phase: "Execute", outcome: "WebMCP", detail: "Structured refund effect accepted", at: "10:42:12.113", state: "complete" },
      { phase: "Verify", outcome: "Verified", detail: "Exact amount and rail confirmed", at: "10:42:12.221", state: "complete" },
    ],
    verification: { state: "VERIFIED", summary: "Observed effect matches the authorized candidate exactly.", checks: ["Amount = $42.00", "Rail = original", "Order balance updated"] },
  },
  {
    id: "rejected",
    index: "02",
    label: "Rejected",
    title: "Refund exceeds verified authority",
    description: "The requested amount breaches the actor’s verified policy limit. This is a final denial under the current request, policy, and state.",
    status: "REJECTED",
    request: {
      id: "req_B220",
      intent: "Refund an unsatisfactory purchase",
      actor: "support.agent / marcus",
      target: "order #XC-3911",
      proposedEffect: "Issue $120.00 to original payment method",
    },
    resolution: {
      resolved: [
        { label: "Order total", value: "$148.00", source: "verified", provenance: "Orders API · ord_3911" },
        { label: "Refund limit", value: "$75.00", source: "verified", provenance: "Commerce Policy v3.4" },
        { label: "Requested amount", value: "$120.00", source: "reported", provenance: "Request payload" },
      ],
      unresolved: [],
      commitConstraints: [{ label: "Authority exceeded", detail: "$120.00 request is $45.00 above the verified limit.", condition: "limit", satisfied: false }],
    },
    evidence: [
      { id: "ev_201", claim: "Requested refund is $120.00", source: "Request payload", kind: "reported", boundAt: "11:07:43.111" },
      { id: "ev_202", claim: "Actor limit is $75.00", source: "Commerce Policy v3.4", kind: "verified", boundAt: "11:07:43.119" },
    ],
    reasoning: { involved: false, summary: "Not invoked", output: "A policy-limit breach is deterministic; reasoning cannot expand authority." },
    commit: {
      summary: "Final denial under the current request, policy, and state.",
      policy: "FAIL · $120.00 > $75.00",
      authority: "PASS · actor authority allowed",
      capability: "PASS · refund:create",
      stateBinding: "PASS · candidate state is current",
      baseHash: "921d…110c",
      currentHash: "921d…110c",
    },
    decision: { finality: "FINAL", label: "Final denial", nextStep: "Change the request, policy, or relevant state before asking Xact for a new decision." },
    execution: { selected: "NONE", effect: "No effect released", executed: false, receipt: "—" },
    trace: [
      { phase: "Resolve", outcome: "R3 · U0 · C1", detail: "Policy-limit constraint identified", at: "11:07:43.124", state: "complete" },
      { phase: "Reason", outcome: "Skipped", detail: "Constraint breach is deterministic", at: "11:07:43.126", state: "complete" },
      { phase: "Commit", outcome: "Rejected", detail: "Verified limit exceeded", at: "11:07:43.138", state: "blocked" },
      { phase: "Execute", outcome: "Blocked", detail: "No authorized effect emitted", at: "—", state: "pending" },
      { phase: "Verify", outcome: "Not run", detail: "No effect to verify", at: "—", state: "pending" },
    ],
    verification: { state: "BLOCKED", summary: "No mutation occurred. The consequence boundary held.", checks: ["No execution receipt", "Order balance unchanged", "Rejection audited"] },
  },
  {
    id: "escalated",
    index: "03",
    label: "Escalated",
    title: "Semantic judgment requires review",
    description: "Additional resolution or authority is required. New governed evidence may re-enter Xact for a new Commit decision.",
    status: "ESCALATED",
    request: {
      id: "req_70EA",
      intent: "Grant a service-recovery credit",
      actor: "support.agent / priya",
      target: "account #AC-7782",
      proposedEffect: "Apply a $60.00 account credit",
    },
    resolution: {
      resolved: [
        { label: "Outage duration", value: "47 min", source: "verified", provenance: "Status telemetry · incident 441" },
        { label: "SLA threshold", value: "30 min", source: "verified", provenance: "Enterprise SLA v2.1" },
      ],
      unresolved: [{ label: "Material impairment", detail: "Did the outage materially impair the customer’s scheduled launch?" }],
      commitConstraints: [{ label: "Evidence gap", detail: "Customer report and system telemetry establish impact differently.", condition: "conflict", satisfied: false }],
    },
    evidence: [
      { id: "ev_301", claim: "Service unavailable for 47 minutes", source: "Status telemetry / incident 441", kind: "verified", boundAt: "12:18:02.440" },
      { id: "ev_302", claim: "Launch workflow was blocked", source: "Customer incident report", kind: "reported", boundAt: "12:18:02.451" },
      { id: "ev_303", claim: "Impact appears material", source: "O-Agent structured assessment", kind: "derived", boundAt: "12:18:03.907" },
    ],
    reasoning: { involved: true, summary: "Invoked for U1 only", output: "Proposed finding: material impairment is plausible; confidence is not authorization." },
    commit: {
      summary: "Not denied: resolve the missing authority, then re-enter Xact for a new Commit decision.",
      policy: "HOLD · reviewer required",
      authority: "HOLD · additional authority required",
      capability: "PASS · credit:create",
      stateBinding: "PASS · candidate state is current",
      baseHash: "118a…7f02",
      currentHash: "118a…7f02",
    },
    decision: { finality: "REENTRY_ALLOWED", label: "Re-entry available", nextStep: "Resolve the missing semantics or authority, bind new evidence, and re-enter Xact for a new Commit decision." },
    execution: { selected: "NONE", effect: "Await governed review", executed: false, receipt: "—" },
    trace: [
      { phase: "Resolve", outcome: "R2 · U1 · C1", detail: "Semantic field isolated", at: "12:18:02.467", state: "complete" },
      { phase: "Reason", outcome: "O-Agent", detail: "Structured evidence returned to Xact", at: "12:18:03.907", state: "complete" },
      { phase: "Commit", outcome: "Escalated", detail: "Human approval required", at: "12:18:03.922", state: "active" },
      { phase: "Execute", outcome: "Pending", detail: "No effect authorized", at: "—", state: "pending" },
      { phase: "Verify", outcome: "Not run", detail: "No effect to verify", at: "—", state: "pending" },
    ],
    verification: { state: "NOT_RUN", summary: "Verification waits because Commit has not authorized an effect.", checks: ["Review task created", "Evidence bundle sealed", "No account mutation"] },
  },
  {
    id: "stale",
    index: "04",
    label: "Stale",
    title: "Candidate state changed before Commit",
    description: "The proposal was valid against its base state, but a concurrent refund changed the order before Commit re-read it.",
    status: "STALE",
    request: {
      id: "req_F913",
      intent: "Refund a duplicate charge",
      actor: "billing.agent / devon",
      target: "order #XC-9050",
      proposedEffect: "Issue $36.00 to original payment method",
    },
    resolution: {
      resolved: [
        { label: "Duplicate charge", value: "$36.00", source: "verified", provenance: "Payments API · ch_991" },
        { label: "Refund limit", value: "$75.00", source: "verified", provenance: "Commerce Policy v3.4" },
      ],
      unresolved: [{ label: "Charge equivalence", detail: "Do the two payment records represent the same customer intent?" }],
      commitConstraints: [{ label: "State drift", detail: "A concurrent refund changed refundable balance from $36.00 to $0.00.", condition: "freshness", satisfied: false }],
    },
    evidence: [
      { id: "ev_401", claim: "Duplicate $36.00 charge existed", source: "Payments API / ch_991", kind: "verified", boundAt: "14:03:54.014" },
      { id: "ev_402", claim: "Charge records represent one purchase intent", source: "O-Agent structured assessment", kind: "derived", boundAt: "14:03:54.987" },
      { id: "ev_403", claim: "Refundable balance is now $0.00", source: "Commit re-read / order XC-9050", kind: "verified", boundAt: "14:03:55.202" },
    ],
    reasoning: { involved: true, summary: "Invoked for U1 only", output: "Proposed finding returned as evidence; Commit must still re-read current state." },
    commit: {
      summary: "Candidate binding no longer matches current state. Effect is discarded.",
      policy: "PASS · amount within limit",
      authority: "PASS · actor authority allowed",
      capability: "PASS · refund:create",
      stateBinding: "FAIL · base hash mismatch",
      baseHash: "ae10…29f1",
      currentHash: "ce44…9a70",
    },
    decision: { finality: "RERESOLUTION_REQUIRED", label: "Fresh resolution required", nextStep: "Resolve against current state before proposing another candidate." },
    execution: { selected: "NONE", effect: "Candidate discarded", executed: false, receipt: "—" },
    trace: [
      { phase: "Resolve", outcome: "R2 · U1 · C0", detail: "One semantic field isolated", at: "14:03:54.041", state: "complete" },
      { phase: "Reason", outcome: "O-Agent", detail: "Structured evidence returned to Xact", at: "14:03:54.987", state: "complete" },
      { phase: "Commit", outcome: "Stale", detail: "Current hash differs from base", at: "14:03:55.205", state: "blocked" },
      { phase: "Execute", outcome: "Blocked", detail: "Stale candidate discarded", at: "—", state: "pending" },
      { phase: "Verify", outcome: "Not run", detail: "No effect to verify", at: "—", state: "pending" },
    ],
    verification: { state: "BLOCKED", summary: "No duplicate refund was issued. Fresh resolution is required.", checks: ["Base hash mismatch recorded", "No execution receipt", "Candidate invalidated"] },
  },
];

export const scenarioById = Object.fromEntries(
  scenarios.map((scenario) => [scenario.id, scenario]),
) as Record<ControlRoomScenario["id"], ControlRoomScenario>;
